Add missing dependency group for async SQLAlchemy tests (#1474)
* Add missing dependency group for async SQLAlchemy tests

FAILED tests/plugins/test_polars_extensions.py::test_polars_database - ImportError: The SQLAlchemy asyncio module requires that the Python 'greenlet' library is installed.  In order to ensure this dependency is available, use the 'sqlalchemy[asyncio]' install target:  'pip install sqlalchemy[asyncio]'

* fix: Set matplotlib to non-interactive backend (Agg) for tests

Workaround for: https://github.com/astral-sh/uv/issues/7036